# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch:
  push:
    types:
      - closed
    branches:
      - release/*
jobs:
  test:
    name: Test Web App
    runs-on: macos-latest
    steps:
      - name: ğŸ— Setup Repo
        uses: actions/checkout@v3
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: ğŸ“¦ Install Dependencies
        run: npm ci
      - name: ğŸ§ª Test app
        run: npm run test

  build_and_deploy:
    needs: test
    name: Deploy on Firebase
    runs-on: macos-latest
    environment: production
    env:
      CONTENTFUL_ACCESS_TOKEN: '${{ secrets.CONTENTFUL_ACCESS_TOKEN }}'
      CONTENTFUL_SPACE_ID: '${{ secrets.CONTENTFUL_SPACE_ID }}'
    steps:
      - name: ğŸ— Setup Repo
        uses: actions/checkout@v3
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
      - name: ğŸ“¦ Install Dependencies and Build
        run: npm ci && npm run build
      - name: ğŸš€ Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRESCOM_CORPORATION_GROUP }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
